# version: 2.1
# orbs:
#   cypress: cypress-io/cypress@1.29.0

# jobs:
#   test:
#     docker:
#       - image: cypress/base:14.16.0
#     steps:
#       - checkout
#       - run: npm install
#       - run: npm ci
#       - run: npm run test_edge_specsInFolder_greenKartCopy_headed_cmr

# workflows:
#   build:
#     jobs:
#       - test
